#ni untuk activity bila create 2 avatar, ports kena berlainan. 
services:
  profile:
    image: redis
    volumes:
      - me:/data

  server:
    image: ghcr.io/infratify/arena-server

  avatar:
    image: ghcr.io/infratify/arena-avatar
    ports:
      - "8080:8080"
    environment:
      NAME: AVATAR1
      COLOR: cyan
      SERVER: server:3000
    depends_on:
      - profile
      - server

  avatar2:
    image: ghcr.io/infratify/arena-avatar
    ports:
      - "8081:8080"
    environment:
      NAME: AVATAR2
      COLOR: black
      SERVER: server:3000
    depends_on:
      - profile
      - server
  
volumes:
  me:

#ni bila connect dengan cikgu punya server. kena buang beberapa part dan gantikan. 

services:
  profile:
    image: redis
    volumes:
      - me:/data

  avatar:
    image: ghcr.io/infratify/arena-avatar
    ports:
      - "8080:8080"
    environment:
      NAME: Syaza
      COLOR: yellow
      SERVER: 13.213.70.70
    depends_on:
      - profile
volumes:
  me: